Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/carbon.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.carbon.com:7050
  - &Farmer
    Name: FarmerMSP
    ID: FarmerMSP
    MSPDir: ../organizations/peerOrganizations/farmer.carbon.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('FarmerMSP.admin', 'FarmerMSP.peer', 'FarmerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('FarmerMSP.admin', 'FarmerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('FarmerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('FarmerMSP.peer')"
  - &Buyer
    Name: BuyerMSP
    ID: BuyerMSP
    MSPDir: ../organizations/peerOrganizations/buyer.carbon.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('BuyerMSP.admin', 'BuyerMSP.peer', 'BuyerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('BuyerMSP.admin', 'BuyerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('BuyerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('BuyerMSP.peer')"
  - &CertifyingAuth
    Name: certifyingAuthMSP
    ID: certifyingAuthMSP
    MSPDir: ../organizations/peerOrganizations/certifyingAuth.carbon.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('certifyingAuthMSP.admin', 'certifyingAuthMSP.peer', 'certifyingAuthMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('certifyingAuthMSP.admin', 'certifyingAuthMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('certifyingAuthMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('certifyingAuthMSP.peer')"
  - &Regulators # Corrected indentation here
    Name: RegulatorsMSP
    ID: RegulatorsMSP
    MSPDir: ../organizations/peerOrganizations/regulators.carbon.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegulatorsMSP.admin', 'RegulatorsMSP.peer', 'RegulatorsMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RegulatorsMSP.admin', 'RegulatorsMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RegulatorsMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegulatorsMSP.peer')"

Capabilities:  
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  Addresses:
    - orderer.carbon.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ThreeOrgsChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer.carbon.com
            Port: 7050
            ClientTLSCert: ../organizations/ordererOrganizations/carbon.com/orderers/orderer.carbon.com/tls/server.crt
            ServerTLSCert: ../organizations/ordererOrganizations/carbon.com/orderers/orderer.carbon.com/tls/server.crt
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Farmer
        - *Buyer
        - *CertifyingAuth
        - *Regulators
      Capabilities: *ApplicationCapabilities
